--Tabela asocjacyjna dla rekwizytów i sztuki

insert into SZ_RK(SZTUKI_SZ_ID, REKWIZYTY_RK_ID)
(SELECT SZTUKI.SZ_ID, REKWIZYTY.RK_ID FROM SZTUKI,REKWIZYTY 
WHERE SZTUKI.NAZWA='Wesele' AND REKWIZYTY.NAZWA='slomiany posag');

insert into SZ_RK(SZTUKI_SZ_ID, REKWIZYTY_RK_ID)
(SELECT SZTUKI.SZ_ID, REKWIZYTY.RK_ID FROM SZTUKI,REKWIZYTY 
WHERE SZTUKI.NAZWA='Kogel Mogel' AND REKWIZYTY.NAZWA='butelka spirytusu');

insert into SZ_RK(SZTUKI_SZ_ID, REKWIZYTY_RK_ID)
(SELECT SZTUKI.SZ_ID, REKWIZYTY.RK_ID FROM SZTUKI,REKWIZYTY 
WHERE SZTUKI.NAZWA='Kaczuszki' AND REKWIZYTY.NAZWA='gumowy nos');

insert into SZ_RK(SZTUKI_SZ_ID, REKWIZYTY_RK_ID)
(SELECT SZTUKI.SZ_ID, REKWIZYTY.RK_ID FROM SZTUKI,REKWIZYTY 
WHERE SZTUKI.NAZWA='Makbet' AND REKWIZYTY.NAZWA='suknia Lady Makbet');

insert into SZ_RK(SZTUKI_SZ_ID, REKWIZYTY_RK_ID)
(SELECT SZTUKI.SZ_ID, REKWIZYTY.RK_ID FROM SZTUKI,REKWIZYTY 
WHERE SZTUKI.NAZWA='Zemsta' AND REKWIZYTY.NAZWA='cegla');

insert into SZ_RK(SZTUKI_SZ_ID, REKWIZYTY_RK_ID)
(SELECT SZTUKI.SZ_ID, REKWIZYTY.RK_ID FROM SZTUKI,REKWIZYTY 
WHERE SZTUKI.NAZWA='Kaczuszki' AND REKWIZYTY.NAZWA='zolty plaszcz');

insert into SZ_RK(SZTUKI_SZ_ID, REKWIZYTY_RK_ID)
(SELECT SZTUKI.SZ_ID, REKWIZYTY.RK_ID FROM SZTUKI,REKWIZYTY 
WHERE SZTUKI.NAZWA='Makbet' AND REKWIZYTY.NAZWA='miecz');

insert into SZ_RK(SZTUKI_SZ_ID, REKWIZYTY_RK_ID)
(SELECT SZTUKI.SZ_ID, REKWIZYTY.RK_ID FROM SZTUKI,REKWIZYTY 
WHERE SZTUKI.NAZWA='Zemsta' AND REKWIZYTY.NAZWA='krokodyl');


--Tabela asocjacyjna dla pracowników i sztuk

INSERT INTO PR_SZ(PRACOWNICY_PR_ID, SZTUKI_SZ_ID)
(SELECT PRACOWNICY.PR_ID, SZTUKI.SZ_ID FROM PRACOWNICY,SZTUKI 
WHERE PRACOWNICY.NAZWISKO='Kwiatkowski' AND SZTUKI.NAZWA='Kogel Mogel');

INSERT INTO PR_SZ(PRACOWNICY_PR_ID, SZTUKI_SZ_ID)
(SELECT PRACOWNICY.PR_ID, SZTUKI.SZ_ID FROM PRACOWNICY,SZTUKI 
WHERE PRACOWNICY.NAZWISKO='Smolarek' AND SZTUKI.NAZWA='Zemsta');

INSERT INTO PR_SZ(PRACOWNICY_PR_ID, SZTUKI_SZ_ID)
(SELECT PRACOWNICY.PR_ID, SZTUKI.SZ_ID FROM PRACOWNICY,SZTUKI 
WHERE PRACOWNICY.NAZWISKO='Nowaczyk' AND SZTUKI.NAZWA='Wesele');

INSERT INTO PR_SZ(PRACOWNICY_PR_ID, SZTUKI_SZ_ID)
(SELECT PRACOWNICY.PR_ID, SZTUKI.SZ_ID FROM PRACOWNICY,SZTUKI 
WHERE PRACOWNICY.NAZWISKO='Mostowiak' AND SZTUKI.NAZWA='Kaczuszki');
